name             'sysutils'
maintainer       'Mevan Samaratunga'
maintainer_email 'mevan.samaratunga@fmr.com'
license          'All rights reserved'
description      'Installs/Configures sysutils'
long_description 'Resources for common environment configurations such as sysctl, users, groups, ssh keys, etc.'
version          '1.0.0'

depends          'apt', '~> 2.4.0'
depends          'yum', '~> 3.2.2'
depends          'sudo', '~> 2.6.0'
